import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './ui/themes/providers';
import '@/app/ui/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bailey NextJS Template',
  description: 'Generated by create next app',
};

// suppressHydrationWarning used to suppress warnings
// from Next-Themes changing themes.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
